### ISSUE TITLE
Mac上貌似不可以

### ISSUE THREAD

**Issue by PengJuWang** [chenjiandongx/torrent-cli#11]
![image](https://user-images.githubusercontent.com/16251010/36960215-e8903be8-2080-11e8-99aa-4cb0c4e08374.png)

**Comment by PengJuWang** [comment]
v0.0.6

**Comment by chenjiandongx** [comment]
```shell
C:\Users\chenjiandongx>torrent-cli -k 水形物语
Crawling data for you.....
磁链: magnet:?xt=urn:btih:EB46A3C863E04AE0990F85D29DE34A0935B4A73B
名称: 水形物语.The.Shape.of.Water.2017.DVD.X264.AAC-99Mp4.mp4
大小: 981.0 MB
日期: 2018-02-23
热度: 32

磁链: magnet:?xt=urn:btih:CDBC9CC3B501E20ED54A5EBE25023D4A192E3A49
名称: 水形物语.The Shape of Water.DVDScr.2017-Forever24
大小: 3.2 GB
日期: 2018-02-22
热度: 1

磁链: magnet:?xt=urn:btih:21E9E3D4A3C84588D6A55B7037ADF783BEB9D8F6
名称: 水形物语.The.Shape.of.Water.2017.中英字幕.DVDScr.AAC.720x384.x264-LOT.mp4
大小: 1.5 GB
日期: 2018-02-22
热度: 31

磁链: magnet:?xt=urn:btih:12469D4FB1C540B3231CB9312D08D6D7F7289A94
名称: 水形物语.The.Shape.of.Water.2017.DVDScr.XVID.AC3.HQ.Hive-中英双字-MP4BA
大小: 1.6 GB
日期: 2018-02-21
热度: 8
```

没 Mac 机器，没办法测试，Windows 上是可行的！

**Comment by chenjiandongx** [comment]
已更新至 V0.0.7

**Comment by archer-bao** [comment]
已经测试，Mac和Linux皆不可用，
报错
> Crawling data for you.....
不过Linux上给出了更多错误信息：
/home/user/.local/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
查了一下版本兼容的问题，但是按照网上的教程卸载重装并不能解决。
另外，想问作者，真的测试过Mac和Linux的兼容性？

**Comment by chenjiandongx** [comment]
使用 Python3 试试看吧，我用 Python3 写的，没在 2 下面做过兼容测试

**Comment by archer-bao** [comment]
用Python3也不行，早上简单看了下代码，第一眼觉得有问题的地方是run()里面有个吞异常的地方，https://github.com/chenjiandongx/torrent-cli/blob/master/torrent.py
第111行，捕获所有异常，但是没有任何处理，没抛出，也没提示。
之后我在这里加了异常输出，看到错误：
> Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
我对html、xml之类的不是很懂，在stackoverflow这里（https://stackoverflow.com/questions/24398302/bs4-featurenotfound-couldnt-find-a-tree-builder-with-the-features-you-requeste）搜索到有人有同样的问题，安装第一个回答尝试了下，问题解决。

**Comment by chenjiandongx** [comment]
喔 我的失误 没把 lxml 写入到依赖里面

**Comment by chenjiandongx** [comment]
不过解决了就好 :)

**Comment by archer-bao** [comment]
哈哈，工具不错！

**Comment by Maru-zhang** [comment]
表示我用Python3.6.1完美支持。
