### ISSUE TITLE
貌似失效了，求大神解决下

### ISSUE THREAD

**Issue by Reinhardt1986** [chenjiandongx/torrent-cli#13]
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts>torrent-cl
i -k 战狼2
Crawling data for you.....
HTTPSConnectionPool(host='www.btyunsou.me', port=443): Max retries exceeded with
 url: /search/%E6%88%98%E7%8B%BC2_ctime_1.html (Caused by NewConnectionError('<u
rllib3.connection.VerifiedHTTPSConnection object at 0x000000000347CBA8>: Failed
to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接
。',))

**Comment by chenjiandongx** [comment]
已更新至 V0.0.7

**Comment by Reinhardt1986** [comment]
非常感谢！
