### ISSUE TITLE
请问作者，这是什么错误？

### ISSUE THREAD

**Issue by bodhisatan** [chenjiandongx/torrent-cli#15]
C:\Users\Bodhisatan>torrent-cli
usage: torrent-cli-script.py [-h] [-k KEYWORD] [-n NUM] [-s SORT_BY]
                             [-o OUTPUT] [-p] [-v]

Magnets-Getter CLI Tools.

optional arguments:
  -h, --help            show this help message and exit
  -k KEYWORD, --keyword KEYWORD
                        magnet keyword.
  -n NUM, --num NUM     magnet number.(default 10)
  -s SORT_BY, --sort-by SORT_BY
                        0: Sort by date锛?: Sort by size. 2: Sort by hot-
                        rank.(default 0)
  -o OUTPUT, --output OUTPUT
                        output file path, supports csv and json format.
  -p, --pretty-oneline  show magnets info with one line.
  -v, --version         version information.
Traceback (most recent call last):
  File "F:\Python27\Scripts\torrent-cli-script.py", line 9, in <module>
    load_entry_point('torrent-cli==0.0.7', 'console_scripts', 'torrent-cli')()
  File "build\bdist.win-amd64\egg\torrent.py", line 55, in command_line_runner
    parser.print_help()
  File "F:\Python27\lib\argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "F:\Python27\lib\argparse.py", line 2354, in _print_message
    file.write(message)
IOError: [Errno 0] Error

C:\Users\Bodhisatan>torrent-cli -k 战狼2
Crawling data for you.....
'utf8' codec can't decode byte 0xc0 in position 32: invalid start byte

**Comment by bodhisatan** [comment]
另外，这是Python3写的还是Python2写的？

**Comment by chenjiandongx** [comment]
使用 python3 编写，没对 python2 做过兼容测试喔

**Comment by bodhisatan** [comment]
恩，我刚刚py3成功了
