### ISSUE TITLE
不抓取？

### ISSUE THREAD

**Issue by tinterking** [chenjiandongx/torrent-cli#16]
搜索后不抓取

tinterking:~$ torrent-cli -k 战狼2
Crawling data for you.....
tinterking:~$

**Comment by chenjiandongx** [comment]
哪个版本？

**Comment by tinterking** [comment]
ubuntu16.04

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/37875362-9091ae72-3070-11e8-8e28-31a7bbe7971a.png)

![image](https://user-images.githubusercontent.com/19553554/37875377-c01237f2-3070-11e8-98f7-dc966f7b480a.png)


ubuntu 16.04, Python3, torrent-cli V0.0.7 实测没问题

**Comment by Titzanyic** [comment]
可能需要开启代理。

**Comment by wogenhaosini** [comment]
torrent-cli V0.0.7 不抓取。

**Comment by chenjiandongx** [comment]
发现爬取的网站好像挂了哈哈哈
