### ISSUE TITLE
编码问题。 

### ISSUE THREAD

**Issue by hhhaiai** [chenjiandongx/torrent-cli#17]
E:\code\sss>torrent-cli -k 战狼2
Crawling data for you.....
'utf8' codec can't decode byte 0xc0 in position 32: invalid start byte

**Comment by chenjiandongx** [comment]
Python2 or Python3？ torrent-cli version?

**Comment by chenjiandongx** [comment]
最好使用 Python3 并将 torrent-cli 更新到最新版就能解决问题。
