### ISSUE TITLE
都依赖那些库？Crawling Exception, may be you should check your network!

### ISSUE THREAD

**Issue by porsion** [chenjiandongx/torrent-cli#5]
linux 下 命令行 torrent-cli -k 雷神3
然后：
Crawling Exception, may be you should check your network!
Crawling Exception, may be you should check your network!
Crawling Exception, may be you should check your network!
Crawling Exception, may be you should check your network!
Crawling Exception, may be you should check your network!
Crawling Exception, may be you should check your network!
Crawling Exception, may be you should check your network!
Crawling Exception, may be you should check your network!
Crawling Exception, may be you should check your network!

这是什么情况？

**Comment by Leonezz** [comment]
同样的问题

**Comment by chenjiandongx** [comment]
![image](https://user-images.githubusercontent.com/19553554/34555198-7523f440-f16b-11e7-9abf-896ce87dab14.png)
依赖库在这里

**Comment by Leonezz** [comment]
大佬是不是因为网站被封了所以爬取失败？



发自我的小米手机
在 陈键冬 <notifications@github.com>，2018年1月4日 下午4:22写道：

[image]<https://user-images.githubusercontent.com/19553554/34555198-7523f440-f16b-11e7-9abf-896ce87dab14.png>
依赖库在这里

**Comment by chenjiandongx** [comment]
是，等我找找看有没有其他网站 😂

**Comment by Leonezz** [comment]
感谢大佬😁



发自我的小米手机
在 陈键冬 <notifications@github.com>，2018年1月4日 下午5:01写道：

是，等我找找看有没有其他网站 😂

**Comment by chenjiandongx** [comment]
@porsion @Leonezz 发布了最新版本 v0.0.5 可以使用 `pip install torrent-cli==0.0.5` 安装使用，如有报错可来这里提 ISSUE。新版本还有热度排序功能

**Comment by Leonezz** [comment]
很棒😁



发自我的小米手机
在 陈键冬 <notifications@github.com>，2018年1月4日 下午6:39写道：

@porsion<https://github.com/porsion> @Leonezz<https://github.com/leonezz> 发布了最新版本 v0.0.5 可以使用 pip install torrent-cli==0.0.5 安装使用，如有报错可来这里提 ISSUE。新版本还有热度排序功能

**Comment by chenjiandongx** [comment]
请及时更新到最新版本 -> v0.0.6
