### ISSUE TITLE
15004

### ISSUE THREAD

**Issue by KnightYao** [chenjiandongx/torrent-cli#6]
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by KnightYao** [comment]
有大佬解答一下吗

**Comment by KnightYao** [comment]
找到问题了，里面那个网站是https不是http，用pip install安装不行

**Comment by chenjiandongx** [comment]
@KnightYao 使用 https 就能成功运行了吗

**Comment by chenjiandongx** [comment]
@KnightYao 我这边的话 http 和 https 都能正常运行

**Comment by KnightYao** [comment]
我这边https可以，http不行，网站登不上

**Comment by chenjiandongx** [comment]
@KnightYao 版本号已更新，谢谢你的贡献。
