### ISSUE TITLE
爬的站点可以增加吗或者怎么更改？

### ISSUE THREAD

**Issue by cdyour** [chenjiandongx/torrent-cli#8]

**Comment by chenjiandongx** [comment]
可以增加，也可以更改，照源码改就可以了。当然你也可以改后 PR 过来，我会 review 的

**Comment by cdyour** [comment]
格式是这样吗，一行一个？

> domain = "http://www.btcerise.info"

> domain = "https://www.byyunsou.me"

**Comment by cililianjie** [comment]
不好意思，小白同问，该修改哪个文件，怎么修改？希望哪个大大能看到。谢谢

**Comment by chenjiandongx** [comment]
这个是要修改源码的， https://github.com/chenjiandongx/torrent-cli/blob/master/torrent.py 这个文件
