### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by creboy** [chenjiandongx/torrent-cli#9]
'utf8' codec can't decode byte 0xc0 in position 33: invalid start byte

**Comment by chenjiandongx** [comment]
奇怪，你搜索的是什么内容（不介意的话可以贴出来），我看这边能不能复现问题。

**Comment by creboy** [comment]
C:\Users\Administrator>torrent-cli -k 战狼2
Crawling data for you.....
'utf8' codec can't decode byte 0xc0 in position 33: invalid start byte

**Comment by chenjiandongx** [comment]
你是 V0.0.5 还是 V0.0.6？

**Comment by xphi** [comment]
v0.0.6 出现相同的问题

**Comment by chenjiandongx** [comment]
请更新至 V0.0.7
